import React from "react";

function TncLayout() {
  return (
    <div style={{marginRight:40, marginTop:30, marginLeft:40}}>
      <h3 className="text-center" >TeraBlock Terms of Use</h3>
      <div>
        <p>
        Welcome to TeraBlock ! 
        </p>
        <p>
        This Terms of Use is a binding legal agreement between you and TeraBlock.
        </p>

        By accessing or using the Services in any way, including without limitation by visiting the Website and/or connecting your Wallet to the Services, you represent that,

        1. You have read, understand, and agree to be bound by these Terms of Use; 
        2. You are of legal age to form a binding contract with us; and 
        3. You have the authority to enter into these Terms of Use. 

        <h5>IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF USE, YOU MAY NOT ACCESS OR USE THE SERVICES.</h5>

        <p>
        Your use of, and participation in, certain Services may be subject to Supplemental Terms, which will either be listed in the Terms of Use or will be presented to you for your acceptance when you sign up to use the supplemental Service. If the Terms of Use are inconsistent with the Supplemental Terms, the Supplemental Terms shall control with respect to such Service. The Services allow users to discover, track and interact with data generated by compatible third-party blockchain applications.

        TeraBlock is not a broker, financial institution or intermediary and is in no way your agent, advisor, or custodian. TeraBlock is a non-custodial platform. TeraBlock cannot initiate a transfer of any of your cryptocurrency or digital assets or otherwise access your digital assets. TeraBlock has no fiduciary relationship or obligation to you regarding any decisions or activities that you effect in connection with your use of the Services. Unless explicitly provided in writing, TeraBlock does not host or maintain ecosystem partners accessible on our Services, do not participate in any transactions on such ecosystem partners’ platforms, and TeraBlock does not recommend, endorse, or otherwise take a position on your use of these services.

        TeraBlock is not capable of performing transactions or sending transaction messages on your behalf. All transactions initiated through our Services are effected by your wallet or other third-party digital wallet extensions. By using our Services you agree that such transactions are governed by the terms of service and privacy policy of the applicable extensions.

        Please note that the Agreement is subject to change by TeraBlock in its sole discretion at any time. When changes are made, TeraBlock will make a new copy of the Terms of Use Agreement available at within the Services and any new Supplemental Terms will be made available from within, or through, the affected Service. We will also update the “Last Updated” date at the top of the Terms of Use Agreement. Any changes to the Agreement will be effective immediately for new and old users of the Website and/or Services. TeraBlock may require you to provide consent to the updated Agreement in a specified manner before further use of the Website and/or the Services is permitted. If you do not agree to any change(s), you shall stop using the Website and/or the Services. Otherwise, your continued use of the Website and/or Services constitutes your acceptance of such change(s). 
        </p>
        <h5>PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT TERMS.</h5>
        <h6>I. DEFINITIONS.</h6>
        <ol type="a">
          <li>"Adapter" means a software tool that enables and facilitates the interoperability of a particular DeFi project with the Services.</li>
          <li>"Agreement" means this Terms of Use and any Supplemental Terms applicable to your use of the Services.</li>
          <li>"Arbitration Agreement" means the dispute resolution mechanism in Section 13.</li>
          <li>"Brand" means, with respect to any Adapter, the trademark, logo, or other indicators of identity of the DeFi project or other third-party entity the interoperability of which is facilitated by such Adapter.</li>
          <li>"Connected Content" means any Content or personal financial data that you have provided to and stored in your Wallet.</li>
          <li>"Content" means any information, data, text, software, music, sound, photographs, graphics, video, messages, tags and/or other materials.</li>
          <li>"Digital Asset" means any cryptocurrency, cryptoasset, blockchain-based token, or other digital asset supported by the Services.</li>
          <li>"Ecosystem Partner" means certain supported DeFi applications and projects.</li>
          <li>"Make Available" means to upload, post, e-mail, transmit or otherwise make available through the Services.</li>
          <li>"OSS" or "Open-Source Software" means any software or components thereof subject to “open source” or “free software” licenses.</li>
          <li>"Registered User" is a user who has a valid Third-Party Account, including without limitation a Wallet, through which the user has connected to the Services.</li>
          <li>"Services" means any products and services made available by TeraBlock, including without limitation the Website.</li>
          <li>"Supplemental Terms" means any terms or policies applicable to any products or services offered by TeraBlock that are not addressed in these Terms of Use.</li>
          <li>"Terms of Use" means this TeraBlock Terms of Use Agreement that governs your access to and use of the Services.</li>
          <li>"Third-Party Account" means a valid account on a third-party service provider supported by the Services or a valid third-party Wallet compatible with the Services.</li>
          <li>"Third-Party Services" means third-party websites, applications, and advertisements for third parties accessible or otherwise connected to the Services but not provided by TeraBlock.</li>
          <li>"User Content" means any Content that is Made Available by Registered Users on or through the Services.</li>
          <li>"Wallet" means a software-based system for secure storage of cryptocurrency, cryptoassets, and payment information related thereto.</li>
          <li>"Website" means www.terablock.com and any associated subdomains.</li>
          <li>"You" means the individual or legal entity, as applicable, that is using or accessing the Services, or that is identified as the user when you registered on the Services.</li>
          <li>"TeraBlock", "we", "us" means TeraBlock Technologies Ltd.</li>
          <li>"TeraBlock Parties" means TeraBlock, its parents, subsidiaries, affiliates, officers, employees, agents, partners, suppliers, and licensors.</li>
        </ol>
        <ol type="1">
          <li><span style={{fontWeight:"bold"}}>USE OF THE SERVICES</span>
            <ol type="1">
              <li>License to the Services. The Services are protected by copyright laws throughout the world. Subject to the Agreement, TeraBlock grants you a limited license to reproduce portions of the Services for the sole purpose of using the Services for your personal or internal business purposes. Unless otherwise specified by TeraBlock in a separate license, your right to use any and all the Services is subject to the Agreement.</li>
              <li>Updates. You understand that the Services are evolving. You acknowledge and agree that TeraBlock may update the Services with or without notifying you. You may need to update third-party software from time to time in order to use the Services.</li>
            </ol>
          </li>
          <li>

          </li>

        </ol>
      </div>
    </div>
  );
}

export default TncLayout;
